@TaskManager.Api_HostAddress = http://localhost:5004

POST http://localhost:5004/api/tasks
Content-Type: application/json

{
    "title": "Nueva Tarea",
    "description": "Descripción de la nueva tarea",
    "priority": "High",
    "dueDate": "2026-02-02T23:59:59Z",
    "categoryId": 1
}

###

GET http://localhost:5004/api/tasks
Accept: application/json

###
