@base_url = http://localhost:5004/api

POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "Nueva Tarea",
    "description": "Descripción de la nueva tarea",
    "priority": "High",
    "dueDate": "2026-02-10T23:59:59Z",
    "categoryId": 1
}

###

GET {{base_url}}/tasks

###

GET {{base_url}}/tasks/6

###
PUT {{base_url}}/tasks/2
Content-Type: application/json

{
    "title": "Tarea Actualizada",
    "description": "Descripción actualizada de la tarea",
    "status": "InProgress",
    "priority": "Medium",
    "dueDate": "2026-03-03T23:59:59Z",
    "categoryId": 1
}

###
DELETE {{base_url}}/tasks/1
