@TaskManager.Api_HostAddress = http://localhost:5004

POST http://localhost:5004/api/tasks
Content-Type: application/json

{
    "title": "Nueva Tarea",
    "description": "Descripción de la nueva tarea",
    "priority": "High",
    "dueDate": "2026-02-02T23:59:59Z",
    "categoryId": 1
}

###

GET http://localhost:5004/api/tasks

###

GET http://localhost:5004/api/tasks/1

###
PUT http://localhost:5004/api/tasks/1
Content-Type: application/json

{
    "title": "Tarea Actualizada",
    "description": "Descripción actualizada de la tarea",
    "status": "InProgress",
    "priority": "Medium",
    "dueDate": "2026-03-03T23:59:59Z",
    "categoryId": 1
}

###
DELETE http://localhost:5004/api/tasks/1
